-- ============================================================
-- Migration 019: Coming Soon + Reader Audio (background & voice)
-- ============================================================
-- 1. books.is_coming_soon  → badge "Coming Soon", tidak bisa dibeli/diklaim
-- 2. books.bg_audio_path   → file audio background di bucket private `book-audio`
-- 3. books.voice_audio_path→ file narasi/voice di bucket private `book-audio`
-- 4. Trigger guard: order tidak bisa dibuat untuk buku coming soon (server-side)
-- 5. claim_free_book: tolak buku coming soon
-- 6. Storage bucket `book-audio` (private, akses via edge function get-pdf-url)
-- ============================================================

-- 1-3. Columns
alter table public.books
  add column if not exists is_coming_soon boolean not null default false,
  add column if not exists bg_audio_path text,
  add column if not exists voice_audio_path text;

create index if not exists books_coming_soon_idx
  on public.books (is_coming_soon) where is_coming_soon = true;

-- 4. Server-side guard: block orders on coming-soon books
create or replace function public.block_coming_soon_orders()
returns trigger
language plpgsql security definer set search_path = public
as $$
begin
  if exists (select 1 from public.books b where b.id = new.book_id and b.is_coming_soon = true) then
    raise exception 'This book is not yet available for purchase' using errcode = 'P0001';
  end if;
  return new;
end;
$$;

drop trigger if exists trg_block_coming_soon_orders on public.orders;
create trigger trg_block_coming_soon_orders
  before insert on public.orders
  for each row execute function public.block_coming_soon_orders();

-- 5. claim_free_book: exclude coming-soon books
create or replace function public.claim_free_book(p_book_id uuid)
returns uuid
language plpgsql security definer set search_path = public
as $$
declare
  v_profile_id uuid;
  v_username text;
  v_book_title text;
  v_lib_id uuid;
begin
  select id, username into v_profile_id, v_username
  from public.users_profile
  where auth_user_id = auth.uid() and status = 'active';

  if v_profile_id is null then
    raise exception 'Login required or account disabled' using errcode = '42501';
  end if;

  -- Verify book is free + active + not coming soon
  select title into v_book_title
  from public.books
  where id = p_book_id and is_free = true and status = 'active'
    and is_coming_soon = false;

  if v_book_title is null then
    raise exception 'Book not available for free claim' using errcode = 'P0002';
  end if;

  insert into public.user_library (user_id, book_id, access_status)
  values (v_profile_id, p_book_id, 'active')
  on conflict (user_id, book_id) do update set access_status = 'active'
  returning id into v_lib_id;

  insert into public.activity_logs (action, actor_user_id, actor_username, target_type, target_id, details)
  values (
    'book.claim_free',
    v_profile_id, v_username,
    'book', p_book_id::text,
    jsonb_build_object('title', v_book_title)
  );

  return v_lib_id;
end;
$$;

grant execute on function public.claim_free_book(uuid) to authenticated;

-- 6. Private storage bucket for audio (bg + voice). 50MB limit per file.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('book-audio', 'book-audio', false, 52428800,
        array['audio/mpeg','audio/mp4','audio/aac','audio/ogg','audio/wav','audio/x-m4a'])
on conflict (id) do nothing;

-- Storage policies: only admin can upload/manage audio files.
-- Read access is NOT granted to users directly — signed URLs are
-- generated by the get-pdf-url edge function (service role) after
-- verifying library access.
drop policy if exists "book_audio_admin_all" on storage.objects;
create policy "book_audio_admin_all" on storage.objects
  for all
  using (
    bucket_id = 'book-audio'
    and exists (
      select 1 from public.users_profile up
      where up.auth_user_id = auth.uid() and up.role = 'admin'
    )
  )
  with check (
    bucket_id = 'book-audio'
    and exists (
      select 1 from public.users_profile up
      where up.auth_user_id = auth.uid() and up.role = 'admin'
    )
  );
